" Default location: ~/.vimrc
" Pathogen package manager
execute pathogen#infect()

" ------------------------------------------------------------------------------
" --------------------------------- Key bindings -------------------------------
" ------------------------------------------------------------------------------

" New line without insert
nnoremap <leader>o o<Esc>k
nnoremap <leader>O O<ESC>j

" Split switches
nnoremap <C-j> <C-W><C-J>
nnoremap <C-k> <C-W><C-K>
nnoremap <C-h> <C-W><C-H>
nnoremap <C-l> <C-W><C-L>

" Ctrl+s for saving
nnoremap <C-s> :w<Enter>

" Keybinding for yanking and pasting from system keyboard
noremap <leader>p "+p
noremap <leader>P "+P
noremap <leader>y "+y

" resize horizontal splits
nnoremap <C-S-r>p :res +5<CR>
nnoremap <C-S-r>m :res -5<CR>

"resize vertical splits
nnoremap <C-r>p :vertical resize +5<CR>
nnoremap <C-r>m :vertical resize -5<CR>

" change register leader key
nnoremap <space> "



" ------------------------------------------------------------------------------
" --------------------------------- General ------------------------------------
" ------------------------------------------------------------------------------
" turn off compat mode for vi
set nocompatible 

" syntax highlighting
syntax on 

" spell check
set spell

" (relative) line numbers
set number
set relativenumber

" Indent configuration
filetype plugin indent on
set tabstop=4
set shiftwidth=0
set smarttab
set expandtab
set autoindent
set breakindent

" Show trailing whitespaces
set listchars=tab:•\ ,trail:•,extends:»,precedes:« 
set invlist

" Search
set ignorecase
set smartcase

" create tags file relative to pwd instead of file
set cpo+=d

" folding
set foldmethod=syntax
set foldlevelstart=0
let javaScript_fold=1         " JavaScript
let perl_fold=1               " Perl
let php_folding=1             " PHP
let r_syntax_folding=1        " R
let ruby_fold=1               " Ruby
let sh_fold_enabled=1         " sh
let vimsyn_folding='af'       " Vim script
let xml_syntax_folding=1      " XML


" ------------------------------------------------------------------------------
" ---------------------------------- Appearance --------------------------------
" ------------------------------------------------------------------------------
" Good color alts: monokai (sublime default), one (atom default), OceanicNext
set t_Co=256
colo quantum
let g:airline_theme='badwolf' " reset nice airline theme
hi Normal ctermbg=none



" ------------------------------------------------------------------------------
" ------------------------------- Functions ------------------------------------
" ------------------------------------------------------------------------------
function! s:DiffWithSaved()
  let filetype=&ft
  diffthis
  vnew | r # | normal! 1Gdd
  diffthis
  exe "setlocal bt=nofile bh=wipe nobl noswf ro ft=" . filetype
endfunction
com! DiffSaved call s:DiffWithSaved()


" ------------------------------------------------------------------------------
" ---------------------------------- Plugins -----------------------------------
" ------------------------------------------------------------------------------


" --------------------------------- Airline ------------------------------------
set laststatus=2 " show always

" ---------------------------- autoformat --------------------------------------
noremap <leader>af :Autoformat<CR>

" ---------------------------------- CtrlP -------------------------------------
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g_ctrlp_working_path_mode = 'ra'

" ------------------------------ Easytag ---------------------------------------
set tags=./.vimtags;
let g:easytags_events = ['BufWritePost']
let g:easytags_python_enabled = 1
let g:easytags_async = 1
let g:easytags_autorecurse = 0
let g:easytags_auto_highlight=0
let g:easytags_updatetime_min = 60000 "1min
let g:easytags_dynamic_files = 2

" -------------------------------- NERDTree ------------------------------------
let g:NERDTreeIgnore = ['bin', 'node_modules']
nmap <leader>nt :NERDTreeToggle<CR>

" ------------------------------ python-import ---------------------------------
let g:PythonAutoAddImports = 1 " Autocomplete

" ------------------------------ SimpylFold ------------------------------------
let g:SimpylFold_docstring_preview=1

" ------------------------------- Syntastic ------------------------------------
let g:syntastic_javascript_checkers = ['jshint']

" ------------------------------ Table Mode ------------------------------------
let g:table_mode_header_fillchar= '-'
let g:table_mode_corner="|"
nnoremap <leader>tma :TableModeRealign<CR>

" ------------------------------- Tabular --------------------------------------
nmap <leader>ta= :Tabularize /=<CR>
vmap <leader>ta= :Tabularize /=<CR>
nmap <leader>ta: :Tabularize /:\zs<CR>
vmap <leader>ta: :Tabularize /:\zs<CR>

" ------------------------------ UltiSnips -------------------------------------
let g:UltiSnipsExpandTrigger = "<C-e>"
let g:UltiSnipsJumpForwardTrigger = "<C-S-n>"
let g:UltiSnipsJumpBackwardTrigger = "<C-S-P>"

" ------------------------------ Vim-Latex -------------------------------------
filetype plugin on
set grepprg=grep\ -nH\ $*
filetype indent on
let g:tex_flavor='latex'
nmap <C-Space> <Plug>Tex_FastEnvironmentInsert 
imap <S-CR> <Plug>IMAP_JumpForward
nmap <S-CR> <Plug>IMAP_JumpForward
vmap <S-CR> <Plug>IMAP_JumpForward

" ----------------------------- YouCompleteMe ----------------------------------
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<tab>'
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif
let g:ycm_python_binary_path = 'python' " Enable python autocomplete
let g:EclimCompletionMethod = 'omnifunc' " Use omnifunc for completion
nmap <leader>rr :YcmCompleter RefactorRename 
