# Default location: ~/.zshrc
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
SPACESHIP_VI_MODE_SHOW=false
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_BATTERY_SHOW=false
ZSH_THEME="spaceship"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=7

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git archlinux colored-man-pages zsh-autosuggestions gitfast common-aliases sudo systemd vi-mode wd) 

# User configuration

export PATH="${PATH}:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/android-sdk-linux/platform-tools:$HOME/bin"
# export MANPATH="/usr/local/man:$MANPATH"

# Check for system update if script is in PATH
if system_update_script="$(type -p system-update-prompt)" && [ -n "$system_update_script" ]; then
    # Set the amount of days past for system update prompt
    export UPDATE_SYSTEM_DAYS=3
    # Run the script
    system-update-prompt
fi


source $ZSH/oh-my-zsh.sh
autoload -U zmv 
setopt extendedglob

# Set 256 colors
export TERM="xterm-256color"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='vim'
 fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Disable interactive mode (set by plugin 'common-aliases') for 
# basic commands
unalias rm
unalias mv
unalias cp

alias cd..='cd ..'

alias sd='systemctl poweroff -i'
alias rb='systemctl reboot -i'

alias paccc='sudo pacman -Sc'

# Vim
alias gv='gvim --remote-silent'
alias gvn='gvim -c NERDTree'
alias vin='vim -c NERDTree'

# Git
alias gdt='git difftool'

alias open='xdg-open 2>/dev/null 1>&2'

alias gpu='DRI_PRIME=1'

alias mmv='noglob zmv -W'

# Google Drive
alias dup='drive pull'
alias dupnp='drive pull -no-prompt'
alias dp='drive push'
alias dpnp='drive push -no-promt'
alias ddi='drive diff -skip-content-check'

# tmux
alias tmux='TERM=xterm-256color tmux'
alias tks='tmux kill-session -t'
alias ta='tmux attach -t'
alias tls='tmux ls'
alias tns='tmux new-session -d -s'

# adb
alias adbba="adb backup -apk -obb -all -f"
alias adbb="adb backup -apk -obb -f"
alias adblp='adb shell "pm list packages -f"'

alias rscp='rsync --progress -avz -e ssh'
alias pcp='rsync --info=progress2'

if exa="$(type -p exa)" && [ -n "$exa" ]; then
    alias la='exa -lag --group-directories-first'
    alias l='exa -lg --group-directories-first'
fi

# List directory after cd
function chpwd(){
  emulate -LR zsh
  l
}

# VIM Mode
# bindkey -v
export KEYTIMEOUT=1

# History Control (Arrow up and down use already entered text)
bindkey "^[OA" history-beginning-search-backward
bindkey "^[OB" history-beginning-search-forward
bindkey -M vicmd 'k' history-beginning-search-backward
bindkey -M vicmd 'j' history-beginning-search-forward
bindkey "^?" backward-delete-char
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=reset-prompt-and-accept-line
